# Generated by Django 5.2.16 on 2026-07-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0003_leccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('VIDEO', 'Video'), ('IMAGEN', 'Imagen'), ('ARCHIVO', 'Archivo'), ('CODIGO', 'Código')], max_length=20)),
                ('contenido', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='educacion.leccion')),
            ],
        ),
    ]
