# Generated by Django 5.2.16 on 2026-07-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0004_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('EJERCICIO', 'Ejercicio'), ('CUESTIONARIO', 'Cuestionario'), ('ENTREGA', 'Entrega')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='educacion.leccion')),
            ],
        ),
    ]
