# Generated by Django 5.2.16 on 2026-07-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0005_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('OPCION_MULTIPLE', 'Opción múltiple'), ('VERDADERO_FALSO', 'Verdadero o falso'), ('RESPUESTA_CORTA', 'Respuesta corta'), ('RESPUESTA_LARGA', 'Respuesta larga')], max_length=30)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('puntaje', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='educacion.actividad')),
            ],
        ),
    ]
