# Generated by Django 5.2.16 on 2026-07-23 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0008_alter_actividad_options_alter_contenido_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('ENVIADO', 'Enviado'), ('CALIFICADO', 'Calificado')], default='EN_PROCESO', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='educacion.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de actividad',
                'verbose_name_plural': 'Entregas de actividades',
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(blank=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='educacion.entregaactividad')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seleccionada_en', to='educacion.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_usuarios', to='educacion.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de usuario',
                'verbose_name_plural': 'Respuestas de usuarios',
            },
        ),
    ]
