# Generated by Django 5.2.16 on 2026-07-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0009_entregaactividad_respuestausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='clave_acceso',
            field=models.CharField(blank=True, help_text='Clave requerida para que el alumno pueda iniciar el cuestionario en clase.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entregaactividad',
            name='puntaje_obtenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
