# Generated by Django 5.2.16 on 2026-07-23 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0010_actividad_clave_acceso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaactividad',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Archivo de código o práctico entregado por el estudiante.', null=True, upload_to='entregas_alumnos/'),
        ),
        migrations.AddField(
            model_name='entregaactividad',
            name='comentario_estudiante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('TEORIA', 'Lectura / Video'), ('PRACTICA', 'Práctica de Programación (Subida de Archivo)'), ('CUESTIONARIO', 'Cuestionario / Multiple Choice'), ('EJERCICIO', 'Ejercicio'), ('ENTREGA', 'Entrega')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProgresoTeoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_teoria', to='educacion.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_teoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de teoría',
                'verbose_name_plural': 'Progresos de teorías',
                'unique_together': {('estudiante', 'actividad')},
            },
        ),
    ]
