# Generated by Django 5.2.16 on 2026-07-31 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0011_entregaactividad_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='leccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='educacion.leccion'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='leccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='educacion.leccion'),
        ),
        migrations.CreateModel(
            name='Subleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublecciones', to='educacion.leccion')),
            ],
            options={
                'verbose_name': 'Sublección',
                'verbose_name_plural': 'Sublecciones',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='subleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='educacion.subleccion'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='subleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='educacion.subleccion'),
        ),
    ]
