# Generated by Django 5.2.16 on 2026-07-31 15:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0012_alter_actividad_leccion_alter_contenido_leccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='espacioeducativo',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
