# Generated by Django 5.2.16 on 2026-07-31 16:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0013_alter_actividad_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subleccion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
