# Generated by Django 5.2.16 on 2026-08-07 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0014_subleccion_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercambioArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='intercambio_archivos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(blank=True, help_text='Dejar vacío si el archivo es público para todos los alumnos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intercambio de archivo',
                'verbose_name_plural': 'Intercambio de archivos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
