# Generated by Django 5.2.16 on 2026-08-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0016_asistencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
