# Generated by Django 5.2.16 on 2026-08-10 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0017_delete_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año Lectivo')),
                ('fecha_reinicios', models.DateTimeField(auto_now_add=True)),
                ('alumnos_eliminados', models.PositiveIntegerField(default=0)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ciclo Lectivo',
                'verbose_name_plural': 'Registros de Ciclos Lectivos',
                'ordering': ['-fecha_reinicios'],
            },
        ),
    ]
