# Generated by Django 5.2.16 on 2026-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0018_registrociclolectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='permite_entrega_archivos',
            field=models.BooleanField(default=False, help_text='Habilita la opción para que los alumnos puedan adjuntar archivos desde su PC para revisión del docente.', verbose_name='Permitir entrega de archivos'),
        ),
        migrations.AddField(
            model_name='entregaactividad',
            name='comentario_docente',
            field=models.TextField(blank=True, help_text='Devolución u observaciones enviadas por el profesor.', null=True),
        ),
    ]
