# Generated by Django 5.2.16 on 2026-08-07 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(blank=True, help_text='Ejemplo: 6to 1ra, 5to 2da', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dia_cursado',
            field=models.CharField(blank=True, help_text='Ejemplo: Lunes, Miércoles', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HistorialSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de sesión',
                'verbose_name_plural': 'Historiales de sesiones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
