# Generated by Django 5.2.16 on 2026-08-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], default='M', help_text='Turno al que pertenece el alumno (Mañana/Tarde/Noche)', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='curso',
            field=models.CharField(blank=True, help_text='Ejemplo: 5A, 5C, 6to 1ra', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dia_cursado',
            field=models.CharField(blank=True, help_text='Ejemplo: Lunes, Miércoles o Lunes,Martes', max_length=50, null=True),
        ),
    ]
