# Generated by Django 5.2.16 on 2026-08-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_turno_alter_usuario_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialsesion',
            name='equipo',
            field=models.CharField(blank=True, help_text='Identificador de la netbook/computadora (ej. ALUMNO-05 / COMPUTERNAME)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, help_text='Última fecha y hora de actividad/login registrada', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_equipo',
            field=models.CharField(blank=True, help_text='Nombre de la netbook o PC usada en el último inicio de sesión (ej. ALUMNO-05)', max_length=100, null=True),
        ),
    ]
