# Generated by Django 5.2.16 on 2026-08-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='comunicacion/archivos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(blank=True, help_text='Dejar vacío para transmitir a todos los estudiantes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicacion_archivos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacion_archivos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Compartido',
                'verbose_name_plural': 'Archivos Compartidos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionPlataforma',
        ),
        migrations.AlterModelOptions(
            name='mensajechat',
            options={'ordering': ['fecha_envio'], 'verbose_name': 'Mensaje de Chat', 'verbose_name_plural': 'Mensajes de Chat'},
        ),
        migrations.RenameField(
            model_name='mensajechat',
            old_name='emisor',
            new_name='remitente',
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='leido',
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='receptor',
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='sala',
            field=models.CharField(default='general', help_text='Identificador de la sala de chat (ej: general, curso_python, etc.)', max_length=100),
        ),
    ]
