# Generated by Django 5.2.16 on 2026-08-11 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_archivocompartido_delete_configuracionplataforma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(db_index=True, max_length=100)),
                ('puede_hablar', models.BooleanField(default=True)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Chat',
                'verbose_name_plural': 'Permisos de Chat',
                'unique_together': {('sala', 'usuario')},
            },
        ),
    ]
